core/urls.py
from django.contrib import admin
from django.urls import path
from .views import home, lista_funcoes, funcao_novo, funcao_update, funcao_search, funcao_delete
from .views import lista_setores, setor_novo, setor_update, setor_search, setor_delete
from .views import lista_tiporiscos, tiporisco_novo, tiporisco_update, tiporisco_delete
from .views import lista_riscos, risco_novo, risco_update, risco_delete
from .views import lista_exames, exame_novo, exame_update, exame_delete
from .views import lista_grupos, grupo_novo, grupo_update, grupo_delete

urlpatterns = [
    path('home', home, name='home'),
    path('lista_funcoes', lista_funcoes, name='lista_funcoes'),
    path('funcao_novo', funcao_novo, name='funcao_novo'),
    path('funcao_update/<int:id>', funcao_update, name='funcao_update'),
    path('funcao_delete/<int:id>', funcao_delete, name='funcao_delete'),
    path('funcao_search', funcao_search, name='funcao_search'),

    path('lista_setores', lista_setores, name='lista_setores'),
    path('setor_novo', setor_novo, name='setor_novo'),
    path('setor_update/<int:id>', setor_update, name='setor_update'),
    path('setor_delete/<int:id>', setor_delete, name='setor_delete'),
    path('setor_search', setor_search, name='setor_search'),

    path('lista_tiporiscos', lista_tiporiscos, name='lista_tiporiscos'),
    path('tiporisco_novo', tiporisco_novo, name='tiporisco_novo'),
    path('tiporisco_update/<int:id>', tiporisco_update, name='tiporisco_update'),
    path('tiporisco_delete/<int:id>', tiporisco_delete, name='tiporisco_delete'),

    path('lista_riscos', lista_riscos, name='lista_riscos'),
    path('risco_novo', risco_novo, name='risco_novo'),
    path('risco_update/<int:id>', risco_update, name='risco_update'),
    path('risco_delete/<int:id>', risco_delete, name='risco_delete'),

    path('lista_exames', lista_exames, name='lista_exames'),
    path('exame_novo', exame_novo, name='exame_novo'),
    path('exame_update/<int:id>', exame_update, name='exame_update'),
    path('exame_delete/<int:id>', exame_delete, name='exame_delete'),

    path('lista_grupos', lista_grupos, name='lista_grupos'),
    path('grupo_novo', grupo_novo, name='grupo_novo'),
    path('grupo_update/<int:id>', grupo_update, name='grupo_update'),
    path('grupo_delete/<int:id>', grupo_delete, name='grupo_delete'),

]

sgo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

core/models.py
from django.db import models


# Create your models here.
class Funcao (models.Model):
    nome = models.CharField(max_length=50, blank=False, null=False)

    def __str__(self):
        return self.nome

    class Meta:
        db_table = 'funcao'


class Setor (models.Model):
    nome = models.CharField(max_length=50, blank=False, null=False)

    def __str__(self):
        return self.nome

    class Meta:
        db_table = 'setor'


class TipoRisco(models.Model):
    nome = models.CharField(max_length=50, null=False, blank=False)

    def __str__(self):
        return self.nome

    class Meta:
        db_table = 'tiporisco'


class Risco(models.Model):
    nome = models.CharField(max_length=50, null=False, blank=False)
    tiporisco = models.ForeignKey('tiporisco', on_delete=models.CASCADE)
    
    class Meta:
        db_table = 'risco'


class Grupo(models.Model):
    nome = models.CharField(max_length=50, null=False, blank=False)

    def __str__(self):
        return self.nome

    class Meta:
        db_table = 'grupo'


class Exame(models.Model):
    nome = models.CharField(max_length=60, null=False, blank=False)
    validade = models.IntegerField(null=False, blank=False)

    def __str__(self):
        return self.nome

    class Meta:
        db_table = 'exame'


class TipoExame(models.Model):
    nome = models.CharField(max_length=50, null=False, blank=False)

    def __str__(self):
        return self.nome

    class Meta:
        db_table = 'tipoexame'     


class GrupoExame(models.Model):
    grupo = models.ForeignKey('grupo', on_delete=models.PROTECT)
    exame = models.ForeignKey('exame', on_delete=models.PROTECT)
    tipoexame = models.ForeignKey('tipoexame', on_delete=models.PROTECT)

    class Meta:
        db_table = 'grupoexame'


class GrupoFuncao(models.Model):
    grupo = models.ForeignKey('grupo', on_delete=models.PROTECT)
    funcao = models.ForeignKey('funcao', on_delete=models.PROTECT)
    setor = models.ForeignKey('setor', on_delete=models.PROTECT)

    class Meta:
        db_table = 'grupofuncao'


class GrupoRisco(models.Model):
    grupo = models.ForeignKey('grupo', on_delete=models.PROTECT)
    risco = models.ForeignKey('risco', on_delete=models.PROTECT)

    class Meta:
        db_table = 'gruporisco'


class Coordenador(models.Model):
    nome = models.CharField(max_length=50, null=False, blank=False)
    crm = models.CharField(max_length=10, null=False, blank=False)
    data_inicio = models.DateField(null=False, blank=False)
    data_fim = models.DateField(null=True, blank=True)

    class Meta:
        db_table = 'coordenador'


class Empregado(models.Model):
    nome = models.CharField(max_length=50, null=False, blank=False)
    cpf = models.CharField(max_length=15, null=False, blank=False)
    ctps = models.CharField(max_length=20, null=False, blank=False)
    serie = models.CharField(max_length=10, null=False, blank=False)
    data_nascimento = models.DateField(null=False, blank=False)
    data_admissao = models.DateField(null=False, blank=False)
    data_demissao = models.DateField(null=True, blank=True)
    setor = models.ForeignKey('Setor', on_delete=models.PROTECT)
    funcao = models.ForeignKey('Funcao', on_delete=models.PROTECT)
    grupo = models.ForeignKey('Grupo', on_delete=models.PROTECT)

    class Meta:
        db_table = 'empregado'


class Atendimento(models.Model):
    data_atendimento = models.DateField(null=False, blank=False)
    empregado = models.ForeignKey('Empregado', on_delete=models.PROTECT)
    coordenador = models.ForeignKey('Coordenador', on_delete=models.PROTECT)
    setor = models.ForeignKey('Setor', on_delete=models.PROTECT)
    funcao = models.ForeignKey('Funcao', on_delete=models.PROTECT)
    grupo = models.ForeignKey('Grupo', on_delete=models.PROTECT)
    tipoexame = models.ForeignKey('TipoExame', on_delete=models.PROTECT)
    trabalhoaltura = models.BooleanField()
    espacoconfinado = models.BooleanField()
    apto = models.BooleanField()

    class Meta:
        db_table = 'atendimento'


class AtendimentoRisco(models.Model):
    atendimento = models.ForeignKey('Atendimento', on_delete=models.PROTECT)
    risco = models.ForeignKey('Risco', on_delete=models.PROTECT)

    class Meta:
        db_table = 'atendimentorisco'


class AtendimentoExame(models.Model):
    atendimento = models.ForeignKey('Atendimento', on_delete=models.PROTECT)
    exame = models.ForeignKey('Exame', on_delete=models.PROTECT)

    class Meta:
        db_table = 'atendimentoexame'

core/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.http import HttpResponse, HttpRequest
from django.core.paginator import Paginator
from .models import Funcao, Setor, TipoRisco, Risco, Exame, Grupo
from .forms import FuncaoForm, SetorForm, TipoRiscoForm, RiscoForm, ExameForm, GrupoForm

# Create your views here.
def home(request):
    return render(request, 'core/home.html')

def lista_funcoes(request):
    form = FuncaoForm
    funcoes_list = Funcao.objects.all().order_by('nome')
    paginator = Paginator(funcoes_list, 2)
    page = request.GET.get('page')
    funcoes = paginator.get_page(page)
    data = {}
    data['funcoes'] = funcoes
    data['form'] = form
    return render(request, 'core/lista_funcoes.html', data)

def funcao_novo(request):
    if request.method == "POST":
        nome = request.POST.get('nome')
        count = Funcao.objects.filter(nome=nome).count()
        if count > 0:
            messages.error(request, 'Registro já cadastrado com este Nome !')
            return redirect('funcao_novo')
        else:
            form = FuncaoForm(request.POST)
            if form.is_valid():
                form.save()
                return redirect('lista_funcoes')
    else:
        form = FuncaoForm
        return render(request, 'core/funcao_novo.html', {'form': form})

def funcao_update(request, id):
    funcao = Funcao.objects.get(id=id)
    form = FuncaoForm(request.POST or None, instance=funcao)
    data = {}
    data['funcao'] = funcao
    data['form'] = form
    if request.method == "POST":
        if form.is_valid():
            form.save()
            return redirect('lista_funcoes')
    else:
        form = FuncaoForm
        return render(request, 'core/funcao_update.html', data)

def funcao_search(request):
    search = request.GET.get('search')
    funcoes = Funcao.objects.filter(nome__icontains=search)
    form = FuncaoForm()
    data = {}
    data['funcoes'] = funcoes
    data['form'] = form
    return render(request, 'core/lista_funcoes.html', data)

def funcao_delete(request, id):
    funcao = Funcao.objects.get(id=id)
    funcao.delete()
    messages.success(request, 'Registro Excluido com sucesso !')
    return redirect('lista_funcoes')

def lista_setores(request):
    form = SetorForm
    setores_list = Setor.objects.all().order_by('nome')
    paginator = Paginator(setores_list, 2)
    page = request.GET.get('page')
    setores = paginator.get_page(page)
    data = {}
    data['setores'] = setores
    data['form'] = form
    return render(request, 'core/lista_setores.html', data)

def setor_novo(request):
    if request.method == "POST":
        nome = request.POST.get('nome')
        count = Setor.objects.filter(nome=nome).count()
        if count > 0:
            messages.error(request, 'Registro já cadastrado com este Nome !')
            return redirect('setor_novo')
        else:
            form = SetorForm(request.POST)
            if form.is_valid():
                form.save()
                return redirect('lista_setores')
    else:
        form = SetorForm
        return render(request, 'core/setor_novo.html', {'form': form})

def setor_update(request, id):
    setor = Setor.objects.get(id=id)
    form = SetorForm(request.POST or None, instance=setor)
    data = {}
    data['setor'] = setor
    data['form'] = form
    if request.method == "POST":
        if form.is_valid():
            form.save()
            return redirect('lista_setores')
    else:
        form = SetorForm
        return render(request, 'core/setor_update.html', data)

def setor_search(request):
    search = request.GET.get('search')
    setores = Setor.objects.filter(nome__icontains=search)
    form = SetorForm()
    data = {}
    data['setores'] = setores
    data['form'] = form
    return render(request, 'core/lista_setores.html', data)

def setor_delete(request, id):
    setor = Setor.objects.get(id=id)
    setor.delete()
    messages.success(request, 'Registro Excluido com sucesso !')
    return redirect('lista_setores')

def lista_tiporiscos(request):
    form = TipoRiscoForm
    tiporiscos = TipoRisco.objects.all().order_by('nome')
    data = {}
    data['tiporiscos'] = tiporiscos
    data['form'] = form
    return render(request, 'core/lista_tiporiscos.html', data)

def tiporisco_novo(request):
    if request.method == "POST":
        nome = request.POST.get('nome')
        count = TipoRisco.objects.filter(nome=nome).count()
        if count > 0:
            messages.error(request, 'Registro já cadastrado com este Nome !')
            return redirect('tiporisco_novo')
        else:
            form = TipoRiscoForm(request.POST)
            if form.is_valid():
                form.save()
                return redirect('lista_tiporiscos')
    else:
        form = TipoRiscoForm
        return render(request, 'core/tiporisco_novo.html', {'form': form})

def tiporisco_update(request, id):
    tiporisco = TipoRisco.objects.get(id=id)

    nome = request.POST.get('nome')
    count = TipoRisco.objects.filter(nome=nome).exclude(id=id).count()
    if count > 0:
        messages.error(request, 'Registro já cadastrado com este Nome !')
        return redirect('lista_tiporiscos')

    form = TipoRiscoForm(request.POST or None, instance=tiporisco)
    data = {}
    data['tiporisco'] = tiporisco
    data['form'] = form
    if request.method == "POST":
        if form.is_valid():
            form.save()
            return redirect('lista_tiporiscos')
    else:
        form = TipoRiscoForm
        return render(request, 'core/tiporisco_update.html', data)

def tiporisco_delete(request, id):
    tiporisco = TipoRisco.objects.get(id=id)
    tiporisco.delete()
    messages.success(request, 'Registro Excluido com sucesso !')
    return redirect('lista_tiporiscos')

def lista_riscos(request):
    form = RiscoForm
    riscos = Risco.objects.all().order_by('nome')
    data = {}
    data['riscos'] = riscos
    data['form'] = form
    return render(request, 'core/lista_riscos.html', data)

def risco_novo(request):
    if request.method == "POST":
        nome = request.POST.get('id_nome')
        tiporisco_id = request.POST.get('id_tiporisco')
        count = Risco.objects.filter(nome=nome).count()
        if count > 0:
            messages.error(request, 'Registro já cadastrado com este Nome !')
            return redirect('risco_novo')
        else:
            form = RiscoForm(request.POST)
            if form.is_valid():
                form.save()
                return redirect('lista_riscos')
    else:
        form = RiscoForm
        tiporiscos = TipoRisco.objects.all().order_by('nome')
        data = {}
        data['tiporiscos'] = tiporiscos
        data['form'] = form
        return render(request, 'core/risco_novo.html', data)

def risco_update(request, id):
    risco = Risco.objects.get(id=id)
    nome = request.POST.get('nome')
    count = Risco.objects.filter(nome=nome).exclude(id=id).count()
    if count > 0:
        messages.error(request, 'Registro já cadastrado com este Nome !')
        return redirect('lista_riscos')

    form = RiscoForm(request.POST or None, instance=risco)
    tiporiscos = TipoRisco.objects.all().order_by('nome')
    data = {}
    data['tiporiscos'] = tiporiscos
    data['risco'] = risco
    data['form'] = form

    if request.method == "POST":
        if form.is_valid():
            form.save()
            return redirect('lista_riscos')
    else:
        form = RiscoForm
        return render(request, 'core/risco_update.html', data)

def risco_delete(request, id):
    risco = Risco.objects.get(id=id)
    risco.delete()
    messages.success(request, 'Registro Excluido com sucesso !')
    return redirect('lista_riscos')

def lista_exames(request):
    form = ExameForm
    exames = Exame.objects.all().order_by('nome')
    data = {}
    data['exames'] = exames
    data['form'] = form
    return render(request, 'core/lista_exames.html', data)

def exame_novo(request):
    if request.method == "POST":
        nome = request.POST.get('id_nome')
        validade = request.POST.get('validade')
        count = Exame.objects.filter(nome=nome).count()
        if count > 0:
            messages.error(request, 'Registro já cadastrado com este Nome !')
            return redirect('exame_novo')
        else:
            form = ExameForm(request.POST)
            if form.is_valid():
                form.save()
                return redirect('lista_exames')
    else:
        form = ExameForm
        data = {}
        data['form'] = form
        return render(request, 'core/exame_novo.html', data)

def exame_update(request, id):
    exame = Exame.objects.get(id=id)
    form = ExameForm(request.POST or None, instance=exame)
    data = {}
    data['exame'] = exame
    data['form'] = form

    if request.method == "POST":
        nome = request.POST.get('nome')
        count = Exame.objects.filter(nome=nome).exclude(id=id).count()
        if count > 0:
            messages.error(request, 'Registro já cadastrado com este Nome !')
            return redirect('lista_exames')        
        if form.is_valid():
            form.save()
            return redirect('lista_exames')
    else:
        form = ExameForm
        return render(request, 'core/exame_update.html', data)

def exame_delete(request, id):
    exame = Exame.objects.get(id=id)
    exame.delete()
    messages.success(request, 'Registro Excluido com sucesso !')
    return redirect('lista_exames')

def lista_grupos(request):
    form = GrupoForm
    grupos = Grupo.objects.all().order_by('nome')
    data = {}
    data['grupos'] = grupos
    data['form'] = form
    return render(request, 'core/lista_grupos.html', data)

def grupo_novo(request):
    if request.method == "POST":
        nome = request.POST.get('nome')
        count = Grupo.objects.filter(nome=nome).count()
        if count > 0:
            messages.error(request, 'Registro já cadastrado com este Nome !')

core/templates/core/exame_novo.html
{% extends 'base.html' %}

{% block content %}

<div class="titulo">EXAME</div>
<form name="form" id="form" class="form-horizontal" method="post" action="">
    {% csrf_token %}
    <div class="form2">
        <div class="form-group">
            <label class="control-label col-sm-3" for="id_nome">Exame:</label>
            <div class="col-sm-8">
                <input type="text" name="nome" maxlength="50" required id="id_nome">
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-3" for="id_validade">Validade:</label>
            <div class="col-sm-8">
                <input type="number" name="validade" maxlength="50" required id="id_validade">
            </div>
        </div>
        
    </div> 

    <div class="botoes">
        <div class="form-group">
            <Button type = "submit" class = "btn btn-primary btn-lg">
                <span class = "glyphicon glyphicon-plus" 
                style="margin-left: 5px; margin-right: 5px; font-size: 18px; padding-bottom:5px;"> Incluir</span>
            </Button>                
        </div>
    </div>

    {% if messages %}
    <div class="alert alert-warning">
            {% for m in messages %}
                <p {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ m }}</p>
            {% endfor %}
        </div>
    {% endif %}
</form>

{% endblock%}

core/templates/core/funcao_novo.html
{% extends 'base.html' %}

{% block content %}

<div class="titulo">FUNÇÕES</div>
<form name="form" id="form" class="form-horizontal" method="post" action="">
    {% csrf_token %}
    <div class="form1">
        <div class="form-group">
            <label class="control-label col-sm-3" for="nome">Nome:</label>
            <div class="col-sm-8">
                <input type="text" name="nome" maxlength="50" required id="id_nome">
            </div>
        </div>
    </div> <!--Final da div form1-->

    <div class="botoes">
        <div class="form-group">
            <Button type = "submit" class = "btn btn-primary btn-lg">
                <span class = "glyphicon glyphicon-plus" 
                style="margin-left: 5px; margin-right: 5px; font-size: 18px; padding-bottom:5px;"> Incluir</span>
            </Button>                
        </div>
    </div>

    {% if messages %}
    <div class="alert alert-warning">
            {% for m in messages %}
                <p {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ m }}</p>
            {% endfor %}
        </div>
    {% endif %}
</form>

{% endblock%}

core/templates/core/funcao_update.html
{% extends 'base.html' %}

{% block content %}

<div class="titulo">FUNÇÕES</div>
<form name="form" id="form" class="form-horizontal" method="post" action="{% url 'funcao_update' funcao.id %}">
    {% csrf_token %}
    <div class="form1">
        <div class="form-group">
            <label class="control-label col-sm-3" for="nome">Nome:</label>
            <div class="col-sm-8">
                <input type="text" name="nome" maxlength="50" required id="id_nome" value="{{ funcao.nome }}">
            </div>
        </div>
    </div> <!--Final da div form1-->

    <div class="botoes">
        <div class="form-group">
            <Button type = "submit" class = "btn btn-primary btn-lg">
                <span class = "glyphicon glyphicon-plus" 
                style="margin-left: 5px; margin-right: 5px; font-size: 18px; padding-bottom:5px;"> Alterar</span>
            </Button>                
        </div>
    </div>

    <div class="form-group">
        <a href="{% url 'funcao_delete' funcao.id %}"
        <Button type = "submit" class = "btn btn-danger btn-lg" style="float:right; margin-top:-46px;">
            <span class = "glyphicon glyphicon-edit" 
            style="margin-left: 5px; margin-right: 10px; font-size: 18px; padding-bottom:5px;"> Excluir</span>
        </Button>       
        </a>         
    </div>
</form>

{% endblock%}

core/templates/core/grupo_novo.html
{% extends 'base.html' %}

{% block content %}

<div class="titulo">GRUPO HOMOGÊNEO</div>
<form name="form" id="form" class="form-horizontal" method="post" action="">
    {% csrf_token %}
    <div class="form1">
        <div class="form-group">
            <label class="control-label col-sm-3" for="nome">Nome:</label>
            <div class="col-sm-8">
                <input type="text" name="nome" maxlength="50" required id="id_nome">
            </div>
        </div>
    </div> <!--Final da div form1-->

    <div class="botoes">
        <div class="form-group">
            <Button type = "submit" class = "btn btn-primary btn-lg">
                <span class = "glyphicon glyphicon-plus" 
                style="margin-left: 5px; margin-right: 5px; font-size: 18px; padding-bottom:5px;"> Incluir</span>
            </Button>                
        </div>
    </div>

    {% if messages %}
    <div class="alert alert-warning">
            {% for m in messages %}
                <p {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ m }}</p>
            {% endfor %}
        </div>
    {% endif %}
</form>

{% endblock%}

core/templates/core/grupo_update.html
{% extends 'base.html' %}

{% block content %}

<div class="titulo">GRUPOS HOMOGÊNEOS</div>
<form name="form" id="form" class="form-horizontal" method="post" action="{% url 'grupo_update' grupo.id %}">
    {% csrf_token %}
    <div class="form1">
        <div class="form-group">
            <label class="control-label col-sm-3" for="nome">Nome:</label>
            <div class="col-sm-8">
                <input type="text" name="nome" maxlength="50" required id="id_nome" value="{{ grupo.nome }}">
            </div>
        </div>
    </div> <!--Final da div form1-->

    <div class="botoes">
        <div class="form-group">
            <Button type = "submit" class = "btn btn-primary btn-lg">
                <span class = "glyphicon glyphicon-plus" 
                style="margin-left: 5px; margin-right: 5px; font-size: 18px; padding-bottom:5px;"> Alterar</span>
            </Button>                
        </div>
    </div>

    <div class="form-group">
        <a href="{% url 'grupo_delete' grupo.id %}"
        <Button type = "submit" class = "btn btn-danger btn-lg" style="float:right; margin-top:-66px;">
            <span class = "glyphicon glyphicon-edit" 
            style="margin-left: 5px; margin-right: 10px; font-size: 18px; padding-bottom:5px;"> Excluir</span>
        </Button>       
        </a>         
    </div>
</form>

{% endblock%}

core/templates/core/home.html
{% extends 'base.html' %}

{% block content %}
<div id="corpo2"></div>

{% endblock%}

core/templates/core/lista_exames.html
{% extends 'base.html' %}

{% block content %}

<div class="titulo">EXAMES</div>
<form name="form" id="form" class="form-horizontal" method="GET" action="">
    
    <div class="botoes">
        <div class="form-group">
            <a href="{% url 'exame_novo' %}" style="color:#fff" class="btn btn-primary"> 
            <span class = "glyphicon glyphicon-plus" id="search-btn"
            style="margin-left: 5px; margin-right: 10px; font-size: 18px; padding-bottom:5px;"> Novo
            </span></a>                
        </div>
    </div>

    {% if messages %}
    <div class="alert alert-warning">
            {% for m in messages %}
                <p {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ m }}</p>
            {% endfor %}
        </div>
    {% endif %}
    
    <div>
        <table class="table table-striped table-bordered table-hover">
            <thead>
            <tr>
                <th>EXAME</th>
                <th>VALIDADE</th>
                <th width="50">&nbsp;</th>
            </tr>
            </thead>
            <tbody>
            {% for exame in exames%}
            <tr>
                <td>{{ exame.nome }}</td>
                <td>{{ exame.validade }}</td>
                <td style="width:50px; text-align: center;">
                <a href="{% url 'exame_update' exame.id %}" style="color:#fff" class="btn btn-primary">
                <span class = "glyphicon glyphicon-edit"
                style="margin-left: 5px; margin-right: 5px; font-size: 10px; padding-bottom:5px;">
                </span></a>
                </td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

</form>

{% endblock%}

core/templates/core/lista_funcoes.html
{% extends 'base.html' %}

{% block content %}

<div class="titulo">FUNÇÕES</div>
<form name="form" id="form" class="form-horizontal" method="GET" action="{% url 'funcao_search' %}">
    <div class="form-group row">
        <label for="nome" class="col-sm-2 col-form-label">Função:</label>
        <div class="col-sm-8">
            <input type="text" class="form-control form-control-lg" name="search" id="search" placeholder="Digite a Função para pesquisar">
        </div>
        <div class="col-sm-1">
            <button id="search-btn" type="submit" style="color:#fff" class="btn btn-primary"> 
            <span class = "glyphicon glyphicon-search"
            style="margin-left:5px; font-size: 12px; padding-bottom:5px;">
            </span></Button>
        </div>
    </div>
    
    <div class="botoes">
        <div class="form-group">
            <a href="{% url 'funcao_novo' %}" style="color:#fff" class="btn btn-primary"> 
            <span class = "glyphicon glyphicon-plus" id="search-btn"
            style="margin-left: 5px; margin-right: 10px; font-size: 18px; padding-bottom:5px;"> Novo
            </span></a>                
        </div>
    </div>

    {% if messages %}
    <div class="alert alert-warning">
            {% for m in messages %}
                <p {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ m }}</p>
            {% endfor %}
        </div>
    {% endif %}
    
    <table class="table table-striped table-bordered table-hover">
        <thead>
        <tr>
            <th>FUNÇÃO</th>
            <th width="50">&nbsp;</th>
        </tr>
        </thead>
        <tbody>
        {% for funcao in funcoes%}
        <tr>
            <td>{{ funcao.nome }}</td>
            <td style="width:50px; text-align: center;">
            <a href="{% url 'funcao_update' funcao.id %}" style="color:#fff" class="btn btn-primary">
            <span class = "glyphicon glyphicon-edit"
            style="margin-left: 5px; margin-right: 5px; font-size: 10px; padding-bottom:5px;">
            </span></a>
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>

<div class="pagination">
    <span class="step-links">
    {% if funcoes.has_previous %}
        <a href="?page={{ funcoes.previous_page_number }}">
        <span class = "glyphicon glyphicon-arrow-left"
        style="margin-left: 5px; margin-right: 10px; font-size: 18px; padding-bottom:5px;"> 
        </span></a>
    {% endif %}
    </span>

    <span>
        {{ funcoes.number }} de {{ funcoes.paginator.num_pages }}
    </span>

    <span>
    {% if funcoes.has_next %}
        <a href="?page={{ funcoes.next_page_number }}">
        <span class = "glyphicon glyphicon-arrow-right"
        style="margin-left: 5px; margin-right: 10px; font-size: 18px; padding-bottom:5px;"> 
        </span></a>
    {% endif %}
    </span>
</div>
</form>

{% endblock%}